config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: 'texts#index'
  resources :texts
    resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/text.rb
class Text < ApplicationRecord
  has_one_attached :image

  def was_attached?
    self.image.attached?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]
  validates :nickname, presence: true
  validates :lastname, presence: true
  validates :firstname, presence: true
  has_many :sns_credentials
  has_many :text
  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
        email: auth.info.email
    )
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
 
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :lastname, :firstname, :birthday])
  end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController

  def index
    @texts = Text.all.order(id: "DESC")
  end

  def new
    @text = Text.new
  end

  def create
    Text.create(text_params)
  end

  def destroy
    @text = Text.find(params[:id])
    @text.destroy
  end

  def edit
    @text = Text.find(params[:id])
  end

  def update
    @text = Text.find(params[:id])
    @text.update(text_params)
    redirect_to texts_path
  end


  private
  def text_params
    params.require(:text).permit(:day, :place, :classname, :freedom, :image)
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def google_oauth2
    authorization
   end
  
   private
  
   def authorization
     sns_info  = User.from_omniauth(request.env["omniauth.auth"])
     @user = sns_info[:user]

     if @user.persisted? 
      sign_in_and_redirect @user, event: :authentication
    else 
      @sns_id = sns_info[:sns].id
      render template: 'devise/registrations/new'
    end
  end
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
   def create
    if params[:sns_auth] == 'true'
      pass = Devise.friendly_token
      params[:user][:password] = pass
      params[:user][:password_confirmation] = pass
    end
     super
   end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  
  def new
  @text = Text.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nikki</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">簡単情報共有メモアプリ</a></h1>
        <div class="user_nav grid-6">
          <a class="post" href="/texts/new">メモを書く</a>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer>
      <p>
      
      </p>
    </footer>
  </body>
</html>

app/views/texts/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>保存が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/texts/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>削除が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/texts/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>編集する</h3>
    <%= form_with(model: @text, local: true) do |form| %>
      <%= form.text_field :day, placeholder: "日時" %>
      <%= form.text_field :classname, placeholder: "" %>
      <%= form.text_field :place, placeholder: "場所" %>
      <%= form.text_area :freedom, placeholder: "内容", rows: "10" %>
      <%= form.submit "保存", id: "submit" %>
      <div id="list">
　　　　</div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= form.file_field :image, id:"text-image" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/texts/index.html.erb
<%= render "users/header" %>
<div class="contents_row">
  <% @texts.each do |text| %>
   <div class= "text-date">
    <div class="content_post" style="background-image: url(<%= text.image %>);">
      <span class="day">
        <%= text.day %>
      </span>
      <div class= "textmap">
      <p><%= text.place %></p>

      <p><%= text.transportation %></p>
      <p><%= text.freedom %></p>
      

      <p><%= text.classname %></p>
         <%= text.freedom %>
      </div>
      <%= image_tag text.image.variant(resize: '500x500'), class: 'text-image' if text.image.attached?%> 

      <p><%= text.classname %></p>
         <%= text.freedom %>
      </div>
      <%= image_tag text.image.variant(resize: '150x150'), class: 'text-image' if text.image.attached?%> 

    </div>
  </div>
    <li>
         <%= link_to '編集', edit_text_path(text.id), method: :get %>
        </li>
        <li>
          <%= link_to '削除', text_path(text.id), method: :delete %>
        </li>
    
   </div>
  <% end %>
</div>

app/views/texts/new.html.erb
<div class="contents row">
  <div class="container">
    <h3></h3>
    <%= form_with(model: @text, local: true) do |form| %>
      <%= form.text_field :day, placeholder: "日時" %>
      <%= form.text_field :classname, placeholder: "階級 名前" %>
      <%= form.text_field :place, placeholder: "場所" %>
      <%= form.text_area :freedom, placeholder: "内容", rows: "10" %>
      <%= form.submit "保存", id: "submit" %>
      <div id="list">
　　　　</div>
      <div class="click-upload">
          <div id="image-list"></div>
        <%= form.file_field :image, id:"text-image" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/users/_header.html.erb
<% if user_signed_in? %>
     <li><%= "#{current_user.nickname}でログイン中" %></li>
     <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
<% else %>
     <p>ログインしていません</p>
     <li><%= link_to 'ログイン', new_user_session_path %></li>
     <li><%= link_to '新規登録', new_user_path %></li>
<% end %>

app/views/users/index.html.erb
<%= link_to "メールアドレスで登録", new_user_registration_path%>
<%= link_to 'Googleで登録', user_google_oauth2_omniauth_authorize_path, method: :post%>